### ISSUE TITLE
% of time spent in GC should probably not count as a regression

### ISSUE THREAD

**Issue by KristofferC** [JuliaCI/BenchmarkTrackers.jl#5]
If you make a function faster while keeping the GC pressure the same the % of time in GC will go up but this is not really a regression.

For example: https://github.com/JuliaCI/BaseBenchmarkReports/blob/master/5e07022/5e07022_vs_1a518ec.md

Wow, finally managed correct repo....

**Comment by jrevels** [comment]
lol at the repo jumping. 

It sounds like the solution here is to predicate GC failure detection on the time ratio. That way, actual GC regressions can still be detected if, for example, the time ratio happened to be `1.0` but the GC ratio was `> 1.0`.

The relevant code here is the [ratiofail function](https://github.com/JuliaCI/BenchmarkTrackers.jl/blob/master/src/metrics.jl#L158), which is currently stupidly simplistic.

**Comment by KristofferC** [comment]
Maybe just absolute GC time?

**Comment by tkelman** [comment]
absolute GC time sounds more relevant to me

**Comment by tkelman** [comment]
I guess there could be cases where total time decreases despite gc time increasing even on an absolute scale (so increasing significantly in terms of percentage), but let's see if that really happens in practice.

**Comment by jrevels** [comment]
Yeah. Another problem is that proportionally irrelevant changes in GC times can cause bogus regression detections (imagine a case where total times could be counted in seconds, and GC times counted in milliseconds).

After some thought, I don't think the change I pushed really resolves this issue. It might be best to just ignore GC for the purposes of regression detection, as the issue title proposes. If somebody makes a change that improves the total time for all benchmarks, the system shouldn't flag a regression on that job because of GC changes. 

Cases where total times are invariant and GC times increase are more interesting (and probably worth inspection, in some situations), but arguably shouldn't be considered regressions either.
